### ISSUE TITLE
License

### ISSUE THREAD

**Issue by egilll** [robertknight/tex-linebreak#12]
Hi and thank you for this project.

I noticed that the package.json file mentions that the project is MIT licensed but that there is no license file attached.

Since (according to the terms) I would have to include the license file in projects that build upon this one, I was hoping to ask, could you perhaps add an explicit license file?

With thanks 🙂

**Comment by robertknight** [comment]
Hello. The [license entry](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license) in package.json is an SPDX identifier. The text for any of the standard licenses can be found at spdx.org, in this case https://spdx.org/licenses/MIT.html. IANAL, but my experience of responding to queries about the legal status of dependencies at work is that package metadata has been considered acceptable evidence, as long as the license is a standard one obviously.

**Comment by egilll** [comment]
Oh okay. I had found [a thread](https://opensource.stackexchange.com/a/7244) saying that it was not sufficient, but I will assume that your confirmation above is explicit enough. Thank you very much.
