### ISSUE TITLE
Using different fonts

### ISSUE THREAD

**Issue by quotentiroler** [robertknight/tex-linebreak#53]
Hi! I was trying to make a figma plugin for hyphenation of a text box.

Workflow: I select a textbox, start the plugin, there I retrieve the text box width and the text, then I run your lib and the text is being modified. 

In theory, it works, but as a result, the hyphenation did not really work.. At some places there is the "-" in the line, not at the end of it.

I assume this is due to fonts not being considered at any place. Is that correct? If yes, how do I make it work with any given font?

Also, I have another question: I noticed that the positions of `const { items, positions } = layoutText` do not log empty space occurences, so I had to make a weird work-around to keep the text from boxes of type "glue". Why is that?

**Comment by quotentiroler** [comment]
> 

`<script type="module">
  import texLinebreak from 'https://esm.sh/tex-linebreak@0.6.0';
  import hypher from 'https://esm.sh/hyphenation.de';
  const { createHyphenator, layoutText } = texLinebreak
  const hyphenate = createHyphenator(hypher);
  const measure = word => word.length * 5;
  var result = "";
  window.addEventListener('message', (event) => {
    const { items, positions } = layoutText(event.data.pluginMessage.text, event.data.pluginMessage.width, measure, hyphenate)
    console.log(items, positions)
    var stack = [];
    for (let i = items.length - 1; i >= 0; i--) {
      if (items[i].type == 'glue')
        stack.push(i)
    }
    positions.forEach(pos => {
      //console.log(pos)
      if (pos.item == stack[stack.length - 1] + 1) {
        result += items[stack[stack.length - 1]].text
        stack.pop();
      }
      const item = items[pos.item]
      // console.log(item)
      const text = item.type === 'box' ? item.text : '-';
      result += text;
      // console.log(result)
    });
    parent.postMessage({ pluginMessage: { type: 'text', result, } }, '*')
  }, false)
</script>`

I think the DOMTextMeasurer is not being used in here. Is there another way to determine font?

**Comment by robertknight** [comment]
> I think the DOMTextMeasurer is not being used in here. Is there another way to determine font?

You're right. Do you realize what part of the code you posted is actually measuring the text?

**Comment by quotentiroler** [comment]
Yes, measure = word.length*5 so it does not really measure the width of a word.

**Comment by quotentiroler** [comment]
It was not possible to do it another way than within this script-tag. I think there are ways to convert figma to html, but it makes more sense to solve this low-level. 

DOMTextMeasurer needs either pdf or html, but I can only get information like font from the figma API. It would be useful to have a TextMeasurer with another measure() function accepts Font styles instead of `context`: Element.

**Comment by robertknight** [comment]
>  It would be useful to have a TextMeasurer with another measure() function accepts Font styles instead of context: Element.

You could copy and adapt the `measureText` function from https://github.com/robertknight/tex-linebreak/blob/7a407e5811c9c99be468118ef30d14676c847bc1/src/util/dom-text-measurer.ts#L61. The `cssFont` argument is a string in the format of the CSS [font](https://developer.mozilla.org/en-US/docs/Web/CSS/font) property.

I can see it would be useful to expose this in the public API of the package.

**Comment by quotentiroler** [comment]
```
  window.addEventListener('message', (event) => {
    const measure = word => measureText("10px Inter", word)
    const { items, positions } = layoutText(event.data.pluginMessage.text, event.data.pluginMessage.width, measure, hyphenate)
    console.log(items, positions)ne at first. 
```

 I have tried to adapt it and console says that the font is now "10px Inter" but hyphenation is still not in place. I guess that it does not really know the font?

**Comment by robertknight** [comment]
> I have tried to adapt it and console says that the font is now "10px Inter" but hyphenation is still not in place. 

Do the results of `measureText` match what you can measure on screen? "Inter" looks like a custom font. Is it loaded in the HTML context where `measureText` is called, or does it only exist in the window that you are sending a message to?

**Comment by quotentiroler** [comment]
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter">
<span id="loader" style="font-family: Inter;">I am used for loading</span>

<script>
  window.onload = function () {
     document.getElementById("loader").style.display = "none"
   }  </script>
```
I also tried
`
var myFont = new FontFace("Inter", "url(https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfAZ9hiA.woff2)");
` - which did not work

But no, the measured widths don't seem to match what I see on the screen.

**Comment by quotentiroler** [comment]
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter">
<div style="text-align: justify">
  <span id="loader" style="font-family: Inter;">I am used for loading</span>
  <br>
  <br>
  <span id="content" style="font-family: Inter">Waiting for text...</span>
</div>
<script type="module">
  window.onload = await function () {
    document.getElementById("loader").innerHTML = "Font loaded";
  }
  import texLinebreak from 'https://esm.sh/tex-linebreak@0.6.0/';
  import hypher from 'https://esm.sh/hyphenation.de';
  const { createHyphenator, layoutText } = texLinebreak
  const hyphenate = createHyphenator(hypher);
  var result = "";

  function measureText(cssFont, text) {
    let measureCtx;
    let canvas;
    canvas = document.createElement('canvas');
    measureCtx = canvas.getContext('2d');
    measureCtx.font = cssFont;
    console.log(measureCtx.font)
    return measureCtx.measureText(text).width;
  }
  window.addEventListener('message', (event) => {
    const measure = word => measureText('400 10px Inter', word)
    document.getElementById("content").innerHTML = event.data.pluginMessage.text;
    const { items, positions } = layoutText(event.data.pluginMessage.text, event.data.pluginMessage.width, measure, hyphenate)
    // console.log(items, positions)
    var stack = [];
    for (let i = items.length - 1; i >= 0; i--) {
      if (items[i].type == 'glue')
        stack.push(i)
    }
    positions.forEach(pos => {
      //console.log(pos)
      if (pos.item == stack[stack.length - 1] + 1) {
        result += items[stack[stack.length - 1]].text
        stack.pop();
      }
      const item = items[pos.item]
      //console.log(item)
      const text = item.type === 'box' ? item.text : '-';
      result += text;
      // console.log(result)
    });
    parent.postMessage({ pluginMessage: { type: 'text', result, } }, '*')
  }, false)
</script>
```

the font is being loaded, but the results are not correct. Probably there is some spacing or margin not being considered. I am kind of stuck

**Comment by quotentiroler** [comment]
It's crazy but it seems like it is working after I reduced the width of the textbox by 2.5% and increase the width of a word by 1%. 

However, the library does not process breaklines in the text properly. But I think it could implemented quickly by resetting the width counter if the glue text contains "\n"

**Comment by robertknight** [comment]
If you want '\n' characters to create new paragraphs, you need to either call `layoutText` separately for each paragraph or use lower-level APIs and insert "penalty" items. `layoutText` assumes its content is a single paragraph with no line breaks.
