### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thomasdeanwhite-papermill** [robertknight/tex-linebreak#84]
Hi and thanks for the library! I was wondering what license the source code falls under? The `package.json` file says MIT but there is no LICENSE file. Please can you add a LICENSE file?

Many thanks!

**Comment by robertknight** [comment]
It is licensed under the [MIT license](https://spdx.org/licenses/MIT.html), per the `package.json` field: https://github.com/robertknight/tex-linebreak/blob/87f3dcc8c612a8881637b3f72985c00ab9499262/package.json#L5.

**Comment by thomasdeanwhite-papermill** [comment]
Thanks Robort and thanks for the great package! Closing this issue
